### ISSUE TITLE
Can't make it use mode="light"

### ISSUE THREAD

**Issue by D00mch** [askfiy/visual_studio_code#2]
```lua
-- packer
{
    "askfiy/visual_studio_code",
    config = function()
        require("visual_studio_code").setup({
            mode = "light",
        })
    end,
}
```

I have it black when I type: `:colorscheme visual_studio_code`

**Comment by askfiy** [comment]
By default, it uses a black theme.When you load from the command line, it will use the black theme.

**Comment by strash** [comment]
Hi! Are there any plans to implement theme selection with `vim.opt.background = "light"/"dark?`

**Comment by D00mch** [comment]
Either supporting `vim.opt.background` or having one more colorscheme `visual_studio_code_light` would be quit handy.

**Comment by askfiy** [comment]
The latest submission has fixed it, you can try it.
