### ISSUE TITLE
CSS syntax highlighting

### ISSUE THREAD

**Issue by rogeriofrsouza** [askfiy/visual_studio_code#5]
Hello 👋🏻 
I just noticed there is some differences on the original VSCode CSS syntax highlighting.
Is there any way to configure those colors? 
I am using Neovim 0.9.2-1 and LunarVim 0.9.0.

### LunarVim
![image](https://github.com/askfiy/visual_studio_code/assets/77423511/efbc1d35-b784-4e50-a176-72dd0f4a4038)

### Visual Studio Code
![image](https://github.com/askfiy/visual_studio_code/assets/77423511/51bd4df7-b078-4d6e-b1be-36148882400e)

**Comment by askfiy** [comment]
fix: [#297](https://github.com/askfiy/visual_studio_code/commit/75995b9cfaad3413cf1ca9a2e9f20b41ce53ae8a)
